import os
import sys
import yaml

PROJECT_DIR = os.path.abspath(os.path.join(os.getcwd()))
workdir: PROJECT_DIR

ENV_FILE     = os.path.join(PROJECT_DIR, "env.yaml")
SCRIPTS_DIR  = os.path.join(PROJECT_DIR, "scripts")
LOGS_DIR     = os.path.join(PROJECT_DIR, "logs")
DATA_DIR     = os.path.join(PROJECT_DIR, "data")
RESULTS_DIR  = os.path.join(PROJECT_DIR, "results")
CONFIG_FILE  = os.path.join(PROJECT_DIR, "config", "config.yaml")
RULES_DIR    = os.path.join(PROJECT_DIR, "workflow", "rules")

COMMON_CONDA_ENV = ENV_FILE

configfile: CONFIG_FILE

sys.path.insert(0, SCRIPTS_DIR)
from util import *

include: os.path.join(RULES_DIR, "validate_datasets.smk")
include: os.path.join(RULES_DIR, "load_data.smk")
include: os.path.join(RULES_DIR, "preprocess_and_split.smk")
include: os.path.join(RULES_DIR, "cross_validation.smk")
include: os.path.join(RULES_DIR, "evaluate_model.smk")

rule all:
    input:
        lambda wc: expand(
            os.path.join(RESULTS_DIR, "{dataset}", "evaluation.csv"),
            dataset=read_valid_datasets(checkpoints.validate_datasets.get().output[0])
        )
